api:
  build: .
  links:
    - mysql
  ports:
    - 20050:5000

mysql:
  image: mysql:5.7.11
  ports:
    - 20051:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: vigor-api
    MYSQL_USER: dev
    MYSQL_PASSWORD: dev